version: "3.9"
services:
  api:
    build: ./services/api
    container_name: spacey-api
    env_file:
      - .env
    networks:
      - spacey-services
    ports:
      - "${PORT}:${PORT}"

  config-service:
    build: ./services/config-service
    container_name: config-service
    env_file:
      - .env
    networks:
      - spacey-services

  user-service:
    build: ./services/user-service
    container_name: user-service
    env_file:
      - .env
    networks:
      - spacey-services

  deck-management-service:
    build: ./services/deck-management-service
    container_name: deck-management-service
    env_file:
      - .env
    networks:
      - spacey-services

  learning-service:
    build: ./services/learning-service
    container_name: learning-service
    env_file:
      - .env
    networks:
      - spacey-services

  reminder-service:
    build: ./services/reminder-service
    container_name: reminder-service
    env_file:
      - .env
    networks:
      - spacey-services

  mongodb:
    image: mongo:5.0.5
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - spacey-services
    volumes:
      - mongodb-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

networks:
  spacey-services:
    name: spacey-services
    driver: bridge

volumes:
  mongodb-data:
    name: "mongodb-data"
