version: "3.9"
services:
  api:
    build: ./services/api
    env_file:
      - .env
    networks:
      - proxy
    ports:
      - "80:80"

  user-service:
    build: ./services/user-service
    env_file:
      - .env
    networks:
      - proxy

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    driver: bridge
