version: "3.9"
services:
  api:
    build: ./services/api
    container_name: spacey-api
    env_file:
      - .env
    networks:
      - spacey-services
    ports:
      - "80:80"

  config-service:
    build: ./services/config-service
    container_name: config-service
    env_file:
      - .env
    networks:
      - spacey-services

  user-service:
    build: ./services/user-service
    container_name: user-service
    env_file:
      - .env
    networks:
      - spacey-services

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - spacey-services

networks:
  spacey-services:
    name: spacey-services
    driver: bridge
