name: Build and Push Docker Image

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
    inputs:
      service_name:
        required: true
        type: string
      service_dir:
        required: true
        type: string
      registry:
        required: false
        type: string
        default: moshrank/spacey

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Test
        run: go test -v ./...

      - name: Build Go App
        run: mkdir ./${{ inputs.service_dir }}/bin && env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -o ./${{ inputs.service_dir }}/bin/main ./${{ inputs.service_dir }}

      - name: Log in to Docker Hub

        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ inputs.registry }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ inputs.service_name }}/
          labels: ${{ steps.meta.outputs.labels }}
          file: ./${{ inputs.service_dir }}/Dockerfile
