name: Build and Push Deck Management Service docker image

on:
  push:
    branches: [master]
    paths:
      - "services/deck-management-service/**"
  workflow_dispatch:

jobs:
  build:
    uses: MoShrank/spacey-backend/.github/workflows/build.yml@master
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    with:
      service_name: deck-management-service
      service_dir: services/deck-management-service
