name: Build and Push API docker image

on:
  push:
    branches: [master]
    paths:
      - "services/api/**"
  workflow_dispatch:

jobs:
  build:
    uses: MoShrank/spacey-backend/.github/workflows/build.yml@master
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      service_name: api
      service_dir: services/api
      repository: api
