name: Build and Push Config Service docker image

on:
  push:
    branches: [master]
    paths:
      - "services/config-service/**"
  workflow_dispatch:

jobs:
  build:
    uses: MoShrank/spacey-backend/.github/workflows/build.yml@master
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      service_name: config-service
      service_dir: services/config-service
      repository: config-service
