name: Build and Push User Service docker image

on:
  push:
    branches: [master, staging]
    paths:
      - "services/user-service/**"
  workflow_dispatch:

jobs:
  build:
    uses: MoShrank/spacey-backend/.github/workflows/build.yml@master
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      service_name: user-service
      service_dir: services/user-service
