name: Test Go

on:
    pull_request:
        branches: [master]
    push:
        branches: [master]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.22.6

            - name: Test
              run: go test -v ./...

            - name: Build
              run: go build -v ./...
